/* Lógico_1: */

CREATE DATABASE CAR_LEASE;

CREATE TABLE CLIENTE (
    Email VARCHAR(50) NOT NULL,
    Cpf INTEGER NOT NULL PRIMARY KEY,
    Logradouro VARCHAR(50) NOT NULL,
    Numero VARCHAR(50) NOT NULL,
    Cidade VARCHAR(50),
    Complemento VARCHAR(50),
    Nome VARCHAR(50)
);

CREATE TABLE MOVIMENTO (
    Data_Dev DATETIME ,
    Total_Pagar MONEY NOT NULL,
    Data_Loc DATETIME,
    Valor_Aluguel MONEY NOT NULL,
    Aluguel VARCHAR(50) NOT NULL,
    Model_Veic VARCHAR(50) NOT NULL ,
    Cod_Locacao INTEGER PRIMARY KEY
);

ALTER TABLE MOVIMENTO
ADD CONSTRAINT FK_MOVIMENTO_Cod_Locacao
FOREIGN KEY (Cod_Locacao) REFERENCES MOVIMENTO(Cod_Locacao);

CREATE TABLE VEICULOS (
    Ano VARCHAR(10) NOT NULL,
    Cor VARCHAR(50) NOT NULL,
    Chassi VARCHAR(50) NOT NULL,
    Desc_Serv VARCHAR(50) NOT NULL,
    Placa VARCHAR(50) NOT NULL PRIMARY KEY
);

ALTER TABLE VEICULOS 
ADD CONSTRAINT FK_VEICULOS_Placa
FOREIGN KEY (Placa) REFERENCES VEICULOS(Placa);

CREATE TABLE OFICINA (
    Data_Serv DATETIME,
    Valor_Serv MONEY NOT NULL,
    Desc_Serv VARCHAR(50) NOT NULL,
    Cnpj INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Telefone INTEGER NOT NULL,
);

CREATE TABLE FUNCIONARIO (
    Cargo VARCHAR(50) NOT NULL,
    Data_nasc DATE,
    Nome VARCHAR(50) NOT NULL
);

CREATE TABLE REQUISICAO (
    FK_OFICINA_Cnpj INTEGER NOT NULL,
    FK_VEICULOS_Placa VARCHAR(50) NOT NULL
);
 
ALTER TABLE REQUISICAO ADD CONSTRAINT FK_REQUISICAO_1
    FOREIGN KEY (FK_OFICINA_Cnpj)
    REFERENCES OFICINA (Cnpj)
    ON DELETE SET NULL;
 
ALTER TABLE REQUISICAO ADD CONSTRAINT FK_REQUISICAO_2
    FOREIGN KEY (FK_VEICULOS_Placa)
    REFERENCES VEICULOS (Placa)
    ON DELETE SET NULL;
